### PR TITLE
replaced references for Visual Studio 2015 Community

### PR DESCRIPTION
**Pull request by misaz**

### CODE REVIEW

**Comment by StefH** [comment]
Please create a VS2015 version from this extension.

**Comment by brunolm** [comment]
I don't know if I should maintain this project, it lacks the ability to use dependencies, for example how would you test some code that requires lodash or jquery?

I was working on a code for it some time ago, but couldn't figure out a nice way to do it.

There is Chutzpah
https://visualstudiogallery.msdn.microsoft.com/f8741f04-bae4-4900-81c7-7c9bfb9ed1fe

That might address it and more things, try checking that out.

**Comment by StefH** [comment]
Hi.

I discovered also Chutzpah and used it in your TSLinq project 😃

See my pull request there.

**Comment by misaz** [comment]
This project is not bad and in very special case is very useful. This special case is when all JS files are combined into one and test runs with this all-in-one file. This is exactly my case.

I think the best way is not to parse tests, but interpret the tests. My idea is, that VS extension will strictly search  files with file extension .test.ts and will interpret it. In this script will be created instance of class Test (class will be integrrated into extension and user gets only .d.ts of this class). This test class, will have methods for many support, for example `import(filename: string)`. And the most important function: `runTestCase(callback: Function)`. This solution will be more extensible. For example I need to run some test in phantom and some tests in node.js. Because Test class It can be implemented by simple property on class Test.

**Pull request merged**
